import { StdlibReplacement } from './types.js';

export const STDLIB_CATALOG: StdlibReplacement[] = [
  // JavaScript / TypeScript
  {
    package: 'is-odd',
    language: 'javascript',
    replacement: 'Modulo operator',
    codeSnippet: 'const isOdd = (n: number) => n % 2 !== 0;',
    category: 'Math/Primitives',
    reason: 'Native arithmetic modulo operator is zero-dependency, type-safe, and infinitely faster.',
  },
  {
    package: 'is-even',
    language: 'javascript',
    replacement: 'Modulo operator',
    codeSnippet: 'const isEven = (n: number) => n % 2 === 0;',
    category: 'Math/Primitives',
    reason: 'Native arithmetic modulo operator is zero-dependency and zero-latency.',
  },
  {
    package: 'left-pad',
    language: 'javascript',
    replacement: 'String.prototype.padStart()',
    codeSnippet: 'str.padStart(targetLength, padString)',
    category: 'String',
    reason: 'Standard ECMAScript String method built into all modern engines.',
  },
  {
    package: 'clone-deep',
    language: 'javascript',
    replacement: 'structuredClone()',
    codeSnippet: 'const copy = structuredClone(originalObject);',
    category: 'Data Structures',
    reason: 'Native global algorithm handles cyclic references, Dates, Sets, Maps, and Arrays out of the box.',
  },
  {
    package: 'deep-clone',
    language: 'javascript',
    replacement: 'structuredClone()',
    codeSnippet: 'const copy = structuredClone(originalObject);',
    category: 'Data Structures',
    reason: 'Native global algorithm handles cyclic references and built-in objects natively.',
  },
  {
    package: 'uuid',
    language: 'javascript',
    replacement: 'crypto.randomUUID()',
    codeSnippet: 'const id = crypto.randomUUID();',
    category: 'Cryptography / IDs',
    reason: 'Built directly into Node.js, Web Crypto, and modern browsers.',
  },
  {
    package: 'nanoid',
    language: 'javascript',
    replacement: 'crypto.randomUUID() / crypto.getRandomValues()',
    codeSnippet: 'const id = crypto.randomUUID();',
    category: 'Cryptography / IDs',
    reason: 'Standard cryptographic UUID generation requires zero dependencies.',
  },
  {
    package: 'axios',
    language: 'javascript',
    replacement: 'globalThis.fetch()',
    codeSnippet: 'const res = await fetch(url, { method: "GET", headers }); const data = await res.json();',
    category: 'HTTP / Networking',
    reason: 'Global fetch is available across Node 18+, Bun, Deno, and all modern browsers.',
  },
  {
    package: 'node-fetch',
    language: 'javascript',
    replacement: 'globalThis.fetch()',
    codeSnippet: 'const res = await fetch(url);',
    category: 'HTTP / Networking',
    reason: 'Native fetch is built directly into modern Node.js runtimes.',
  },
  {
    package: 'mkdirp',
    language: 'javascript',
    replacement: 'fs.mkdirSync(path, { recursive: true })',
    codeSnippet: 'fs.mkdirSync(dirPath, { recursive: true });',
    category: 'Filesystem',
    reason: 'Node.js fs module supports recursive folder creation natively since Node 10.12.0.',
  },
  {
    package: 'rimraf',
    language: 'javascript',
    replacement: 'fs.rmSync(path, { recursive: true, force: true })',
    codeSnippet: 'fs.rmSync(targetPath, { recursive: true, force: true });',
    category: 'Filesystem',
    reason: 'Node.js fs.rm / fs.rmSync natively handles recursive force deletion.',
  },
  {
    package: 'querystring',
    language: 'javascript',
    replacement: 'URLSearchParams',
    codeSnippet: 'const params = new URLSearchParams({ key: "val" }).toString();',
    category: 'Web / URL',
    reason: 'URLSearchParams is the standard WHATWG URL standard class.',
  },
  {
    package: 'query-string',
    language: 'javascript',
    replacement: 'URLSearchParams',
    codeSnippet: 'const params = new URLSearchParams(window.location.search);',
    category: 'Web / URL',
    reason: 'URLSearchParams is the standard WHATWG URL standard class.',
  },
  {
    package: 'dotenv',
    language: 'javascript',
    replacement: 'node --env-file=.env or process.loadEnvFile()',
    codeSnippet: 'node --env-file=.env app.js (or process.loadEnvFile() in Node 20+)',
    category: 'Config / Environment',
    reason: 'Node.js 20+ supports --env-file and process.loadEnvFile() natively without dotenv.',
  },
  {
    package: 'chalk',
    language: 'javascript',
    replacement: 'util.styleText() / ANSI escapes',
    codeSnippet: 'import { styleText } from "node:util"; console.log(styleText("green", "Success"));',
    category: 'CLI / Terminal',
    reason: 'Node 20+ provides util.styleText() natively.',
  },

  // Python
  {
    package: 'pytz',
    language: 'python',
    replacement: 'zoneinfo.ZoneInfo',
    codeSnippet: 'from zoneinfo import ZoneInfo\nfrom datetime import datetime\nnow = datetime.now(ZoneInfo("UTC"))',
    category: 'Date / Time',
    reason: 'Python 3.9+ standard library includes zoneinfo.',
  },
  {
    package: 'simplejson',
    language: 'python',
    replacement: 'json',
    codeSnippet: 'import json\ndata = json.loads(payload)',
    category: 'Data Structures / JSON',
    reason: 'Standard library json module is faster and standardized in Python 3.',
  },
  {
    package: 'requests',
    language: 'python',
    replacement: 'urllib.request / http.client (for light tasks)',
    codeSnippet: 'from urllib.request import urlopen\nwith urlopen(url) as response:\n    body = response.read()',
    category: 'HTTP / Networking',
    reason: 'Standard library urllib suffices for simple HTTP requests without third-party dependencies.',
  },
  {
    package: 'mock',
    language: 'python',
    replacement: 'unittest.mock',
    codeSnippet: 'from unittest.mock import MagicMock, patch',
    category: 'Testing',
    reason: 'Built directly into Python 3 unittest module.',
  },
];

export function findStdlibReplacement(packageName: string): StdlibReplacement | undefined {
  const normalized = packageName.toLowerCase().trim();
  return STDLIB_CATALOG.find((item) => item.package.toLowerCase() === normalized);
}
