import { SecurityRule } from './types.js';

export const BUILTIN_SECURITY_RULES: SecurityRule[] = [
  {
    id: 'SEC-001-HARDCODED-PRIVATE-KEY',
    title: 'Hardcoded Private Key / Certificate',
    severity: 'CRITICAL',
    pattern: /-----BEGIN (?:RSA |EC |OPENSSH |DSA )?PRIVATE KEY-----/,
    impact: 'Exposed cryptographic keys allow unauthorized identity impersonation, decryption of sensitive traffic, and session forging.',
    exploitCondition: 'Source repository or compiled artifact is accessible to unauthorized parties.',
    recommendation: 'Move private keys out of source files and load from secure secret manager or environment variables.',
    falsePositiveConsiderations: 'Test fixture files or mock keys used solely in offline unit tests.',
  },
  {
    id: 'SEC-002-GENERIC-API-SECRET',
    title: 'Potential Hardcoded API Secret / Token',
    severity: 'HIGH',
    pattern: /(?:api_key|apikey|secret_key|private_key|auth_token|client_secret)\s*[:=]\s*['"][a-zA-Z0-9_\-+=/]{16,}['"]/i,
    fileExtensions: ['.ts', '.js', '.tsx', '.jsx', '.py', '.go', '.json', '.yaml', '.yml'],
    impact: 'Leaked API secrets allow attackers to make authenticated requests on behalf of the application.',
    exploitCondition: 'Secret has active privileges and is committed into source control.',
    recommendation: 'Replace hardcoded secret with environment variable (e.g., process.env.API_KEY or os.environ).',
    falsePositiveConsiderations: 'Dummy tokens in test suites or placeholder configurations.',
  },
  {
    id: 'SEC-003-AWS-ACCESS-KEY',
    title: 'Hardcoded AWS Access Key ID',
    severity: 'CRITICAL',
    pattern: /(?:A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}/,
    impact: 'Direct compromise of AWS cloud infrastructure and data stores.',
    exploitCondition: 'Key is valid and active in AWS IAM.',
    recommendation: 'Immediately revoke the key in AWS IAM and use IAM Roles / Instance Profiles or environment variables.',
    falsePositiveConsiderations: 'Invalid example keys in documentation or test mocks.',
  },
  {
    id: 'SEC-004-DANGEROUS-EVAL',
    title: 'Arbitrary Code Execution via eval()',
    severity: 'CRITICAL',
    pattern: /\beval\s*\([^)]+\)/,
    fileExtensions: ['.ts', '.js', '.tsx', '.jsx', '.py'],
    impact: 'Allows remote code execution if untrusted input reaches the evaluation context.',
    exploitCondition: 'User input or external data is passed into eval.',
    recommendation: 'Replace eval() with structured parsing (JSON.parse) or type-safe dispatch logic.',
    falsePositiveConsiderations: 'Safe evaluation of static mathematical expressions in isolated sandbox.',
  },
  {
    id: 'SEC-005-SQL-STRING-CONCAT',
    title: 'Potential SQL Injection via String Concatenation',
    severity: 'HIGH',
    pattern: /(?:query|execute|rawQuery)\s*\(\s*['"`](?:SELECT|INSERT|UPDATE|DELETE|DROP)\s+[^'"`]*\$\{[^}]+\}/i,
    fileExtensions: ['.ts', '.js', '.py'],
    impact: 'Attackers can bypass authentication, read, modify, or delete database tables.',
    exploitCondition: 'User input is interpolated into raw SQL query strings.',
    recommendation: 'Use parameterized queries, prepared statements, or ORM query builders.',
    falsePositiveConsiderations: 'Interpolating validated static table names or constants.',
  },
  {
    id: 'SEC-006-DISABLED-TLS-VERIFICATION',
    title: 'Disabled TLS Certificate Verification',
    severity: 'HIGH',
    pattern: /(?:rejectUnauthorized\s*:\s*false|NODE_TLS_REJECT_UNAUTHORIZED\s*=\s*['"]0['"]|verify\s*=\s*False)/,
    impact: 'Exposes network traffic to Man-in-the-Middle (MITM) attacks and data interception.',
    exploitCondition: 'Application runs on public or untrusted network connections.',
    recommendation: 'Enable TLS verification and configure trusted CA bundles.',
    falsePositiveConsiderations: 'Local development proxies or test mocks.',
  },
  {
    id: 'SEC-007-DANGEROUS-INNER-HTML',
    title: 'Potential Cross-Site Scripting (XSS) via dangerouslySetInnerHTML',
    severity: 'MEDIUM',
    pattern: /dangerouslySetInnerHTML\s*=\s*\{\s*\{\s*__html\s*:\s*[^}]+\}\s*\}/,
    fileExtensions: ['.tsx', '.jsx'],
    impact: 'Attackers can execute arbitrary JavaScript in the user context if input is unsanitized.',
    exploitCondition: 'Unsanitized user-supplied HTML is rendered.',
    recommendation: 'Sanitize HTML with DOMPurify or prefer standard React JSX text rendering.',
    falsePositiveConsiderations: 'Rendering trusted, statically defined markdown or SVG icons.',
  },
  {
    id: 'SEC-008-INSECURE-CORS-WILDCARD',
    title: 'Insecure CORS Wildcard with Credentials',
    severity: 'MEDIUM',
    pattern: /['"]Access-Control-Allow-Origin['"]\s*:\s*['"]\*['"].*credentials/i,
    impact: 'Exposes sensitive user data to unauthorized cross-origin web applications.',
    exploitCondition: 'User visits a malicious site while logged into the vulnerable application.',
    recommendation: 'Specify explicit allowed origins rather than wildcard wildcard origins when credentials are enabled.',
    falsePositiveConsiderations: 'Public unauthenticated API endpoints.',
  },
];
